### ISSUE TITLE
Binary Protocol Support

### ISSUE THREAD

**Issue by valarauca** [aisk/rust-memcache#13]
So I wrote a crate for [Binary Protocol Parsing](https://valarauca.github.io/mbpr/mbpr/index.html)

Would you mind me submitting a pull request to merge my crate in and add binary packet protocol?

**Comment by aisk** [comment]
Certainly yes!

And this repo is in early stage, so please contact me if you got any trouble, thanks.

**Comment by aisk** [comment]
Now using binary protocol already.
