### ISSUE TITLE
how to get byte data use get method

### ISSUE THREAD

**Issue by zhaobingss** [aisk/rust-memcache#16]
how to get byte data use get method

**Comment by aisk** [comment]
Just using:

```rs
let resul: Vec<u8> = client.get("foo").unwrap().unwrap();
```

**Comment by zhaobingss** [comment]
@aisk thank you, I am a newer in rust, can you tell me how to detect the result data type , and how to get all keys from memcached , I can't find the item method . thank you again .

**Comment by aisk** [comment]
You can not do this since memcached itself have no direct way to get all keys from server.

**Comment by zhaobingss** [comment]
can I use the lib to execute memcached command like 'stats items' or 'stats cachedump 1 0 '

**Comment by aisk** [comment]
Sorry you cann't do this currently, but the `stats` function is under planning.
