### ISSUE TITLE
Implement binary version of protocol

### ISSUE THREAD

**Issue by paulosuzart** [aisk/rust-memcache#3]
Do you see any special advantage on implementing binary version?

Bests

**Comment by aisk** [comment]
I think we should support ascii and binary protocol both. And not all the value type is `&[u8]`, we should provide some 'typed' APIs, lile `get_str`, `get_int`.

**Comment by paulosuzart** [comment]
Yes, very good idea.

There is also the way rustc-serialize works. You can simply call
json::encode in any RustcEncode annotated struct. Not sure if they use
reflection.

Do you think it is possible to use rustc-serialize directly without any
extra implementation in rust-memcache regarding serialization? I have to
study more to check the possibilities.

**Comment by aisk** [comment]
I think we should just write bytes to memcache, and use the `flag` field to identity it's type, just like Python memcache client dose, and the flag should be compatible with Python memcache client. See this: https://github.com/linsomniac/python-memcached/blob/master/memcache.py#L891

**Comment by aisk** [comment]
We will wrap libmemcached FFI, so this issue is invalid now.
