### ISSUE TITLE
Support auth

### ISSUE THREAD

**Issue by aisk** [aisk/rust-memcache#38]
https://github.com/memcached/memcached/wiki/SASLHowto

**Comment by dormando** [comment]
Fwiw ascii now has an authentication system: https://github.com/memcached/memcached/blob/1.5.16/doc/protocol.txt#L126 - which should be much easier for people to use than SASL.

**Comment by aisk** [comment]
Cool, SASL is too complex for debug and using, I'll try to support it soon.
