### ISSUE TITLE
ascii protocol support?

### ISSUE THREAD

**Issue by kahing** [aisk/rust-memcache#42]
looks like this crate used to support ascii protocol but now only supports binary protocol?

**Comment by aisk** [comment]
Yes, looks like ascii protocol looks like have no any advantage besides binary protocal. Tell me if you have any use case.

**Comment by kahing** [comment]
The use case is non memcached services that only speak the ASCII memcached protocol.

**Comment by aisk** [comment]
Seems reasonable, I'll try to add the ascii protocol back, thanks for reporting!

**Comment by kahing** [comment]
I know you probably have more important things in your life, but is there a rough estimate of when you will work on this? It's a high priority blocker for us so we may have to come up with other alternatives. We only need `gets` for now so it maybe easier for us to just hack something together for our narrow use case.

**Comment by aisk** [comment]
@kahing Hi I'll try to implement the gets command for ascii protocol tonight and tomorrow. But I can't give you guarantee for these.

**Comment by aisk** [comment]
Hi @kahing , the ascii protocol is supported with some basic commands (within `gets`) on the `ascii` branch. You can take a look at https://github.com/aisk/rust-memcache/blob/ascii/tests/test_ascii.rs for usage.

Now you can use these with specify git as dependence source in your `Cargo.toml`, and I'll merge these and make a release for full commands was supported. And I'll try to not make a breaking change in these branch.

Sorry late for this, the refactor works takes more than I expect.

**Comment by kahing** [comment]
Thanks! I haven't done any rigorous testing but does seem to work as advertised!

**Comment by aisk** [comment]
@kahing Hi the ascii branch is merged to master, and i'm ready to delete that branch, so please change you dependence to the master branch.

**Comment by aisk** [comment]
0.12.0 is released, please use this version in your project.

**Comment by terrynsun** [comment]
Thanks @aisk! I've updated our project.
