### ISSUE TITLE
reading stall data with ascii protocol

### ISSUE THREAD

**Issue by jerryz920** [aisk/rust-memcache#53]
When read timeout occurs on the client, continue to read with the same client can potentially fetch stalled data.

I think the reason is here: 
https://github.com/aisk/rust-memcache/blob/master/src/protocol/ascii.rs#L150-L153
The key is shadowed and the if-branch is broken.

Can you take a look and fix it? Thanks!

**Comment by aisk** [comment]
Sorry for the mistake! I'll fix this it tonight.

**Comment by aisk** [comment]
Fixed in version 0.12.1 .

**Comment by jerryz920** [comment]
Thanks a lot!
