### ISSUE TITLE
Support multiple servers

### ISSUE THREAD

**Issue by paulosuzart** [aisk/rust-memcache#6]
By now the project supports just one server. It is recommended by the memcached project site that clients can hash servers and keys so things go to right location.

**Comment by paulosuzart** [comment]
Just PR https://github.com/mattnenterprise/rust-hash-ring/pulls. Looks good enough. Then we can use it.

**Comment by paulosuzart** [comment]
Please take a look at this code: https://github.com/paulosuzart/rust-memcache/blob/multi-server-support/src/connection.rs#L217

Right now it can already connect to multiple servers. But I suspect a concurrent code like Iron framework or anything like that can have some trouble. Not sure.

**Comment by paulosuzart** [comment]
As you can see, there are two different structs. I decided to keep both because Client adds a little overhead with the consistent hash ring thing. So if the user is comfortable with just one connection, he can use `Connection` directly. But if it sounds ugly we can have Connection as a private thing only. 

Anyway the interface is still Commands trait.

**Comment by aisk** [comment]
I think we should only export `Client` to public. And we can specify which protocol / how many servers to use.
For the hash ring overhead, we can have another struct likes `MultipleConnection`, and our old `Connection`. In the initialize stage we can choose which to use based on the servers tuple's length.

**Comment by paulosuzart** [comment]
I'm just playing aroung an trying to work with a builder that would provide the right implementation of `Commands` but get a type error:
https://github.com/paulosuzart/rust-memcache/blob/uniform-interface/src/lib.rs But don't know how to handle this situation. 

Not sure if it is a good approach. But in the end the lib user would do something like `ClientBuilder::new().text_protocol().add_server("localhost", 2333).with_replicas(2).finalize();`

**Comment by aisk** [comment]
I think just pass a tuple is a google choice, like other language's client dose.
