### ISSUE TITLE
Inconsistency between Binary and ASCII protocols

### ISSUE THREAD

**Issue by letmutx** [aisk/rust-memcache#75]
When using binary protocol, `add`ing a key when it already exists results in `Err(MemcacheError::ServerError(0x02))` (`ResponseStatus::KeyExists` error) but with ASCII protocol, the library returns `Ok(())`. Issue is [here](https://github.com/aisk/rust-memcache/blob/66bd9671df31377f3edf9e4fce7d7aa11615d23f/src/protocol/ascii.rs#L83)

**Comment by aisk** [comment]
Confirmed, I think the binary protocol implementation is right, and it should be a bug on ASCII protocol.

**Comment by letmutx** [comment]
Yes, I will work on a fix.
