### ISSUE TITLE
Recreate Connection object when there are errors

### ISSUE THREAD

**Issue by letmutx** [aisk/rust-memcache#92]
In cases when there's a protocol error, we cannot use the underlying connection anymore because some bytes may be left out in the underlying connection. For the client to automatically recover from these class of errors, we should recreate a connection before we send the next request.

We need not do this for all errors. Only some types of errors like `IOError`, `ClientError`(except `KeyTooLong`), `ServerError`. We need not do this for `CommandError`s.

@aisk What do you think about this?

**Comment by aisk** [comment]
I think we need this function, and with some max reconnecting count for not make too many presures to the memcached when it's gotting some issue?

**Comment by letmutx** [comment]
Sure. One other way is to create a new connection only just before the next request is going to be sent to the server, but it would create latency which may not be desirable.

**Comment by aisk** [comment]
Yes I think the latency is not acceptable for memcached scenario, so I think a basic retry is good and suitable.

**Comment by letmutx** [comment]
This is better handled by wrapping the client in a pool like https://github.com/megumish/r2d2-memcache
